name: 'Generate String'
description: 'Generates a string from the given input'
inputs:
  given_input:
    description: 'The input given'
    required: true
    default: 'No string provided'
outputs:
  string:
    description: 'generated string'
    value: ${{ inputs.given_input }}
runs:
  using: "composite"
  steps:
    - run: echo "string=${{ inputs.given_input }}" >> $GITHUB_OUTPUT
      shell: bash
