name: CI

#controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  #single job named simple
  simple: 
    #dfine the runner that the job runs on
    runs-on: ubuntu-latest
    
    #steps is the tasks that will happen when the job is run
    steps:
      - name: Run a one-line script
        run: echo ${{ secrets.PASSWORD }}
        
  string: 
    runs-on: ubuntu-latest
    outputs: 
          output1: ${{ steps.output_string.outputs.this_output }}
    steps:
      - id: output_string
        run: echo "this_output=Hello, world!" >> "$GITHUB_OUTPUT"
        
  use_output:
    runs-on: ubuntu-latest
    needs: string
    steps:
      - env:
          OUTPUT1: ${{needs.string.outputs.this_output}}
        run: echo "$OUTPUT1"
  
