name: CI

#controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  #single job named simple
  simple: 
    #dfine the runner that the job runs on
    runs-on: self-hosted
    
    #steps is the tasks that will happen when the job is run
    steps:
      - name: Run a one-line script
        run: echo ${{ secrets.PASSWORD }}
        
  string: 
    runs-on: self-hosted
    steps:
      #creating the output file
      - uses: actions/checkout@v3
      - run: echo hello, world! > output.txt
      
      #uploading the artifact
      - uses: actions/upload-artifact@v3
        with:
          name: output.txt
          path: output.txt
      
  use_output:
    strategy:
      matrix:
        number: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    runs-on: self-hosted
    needs: string
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        with:
          name: output.txt
      - name: put output in env variable
        run: echo "output=" >> "$GITHUB_ENV"
          cat output.txt >> "$GITHUB_ENV"
          
          echo "${{ env.output }}"
        
  
