name: CI

#controls when the workflow will run
on: workflow_dispatch
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Turning off GO111MODULE'
        run: echo "GO111MODULE=off" >> $GITHUB_ENV

      - name: 'Run tests'
        run: go test

  #single job named simple
  simple: 
    needs: test
    #dfine the runner that the job runs on
    runs-on: ubuntu-latest
    
    #steps is the tasks that will happen when the job is run
    steps:
      - name: Run a one-line script
        run: echo ${{ secrets.PASSWORD }}
        
  string: 
    runs-on: ubuntu-latest
    steps:
      #creating the output file
      - run: echo hello, world! > output.txt
      
      #uploading the artifact
      - uses: actions/upload-artifact@v3
        with:
          name: output.txt
          path: output.txt
      
  use_output:
    strategy:
      matrix:
        number: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    runs-on: ubuntu-latest
    needs: string
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: output.txt
      - name: output string with matrix number
      
        run: |
          output=`cat output.txt`
          echo "$output - ${{ matrix.number }}"
        
  
