on:
  workflow_call:
    inputs:
      given_input:
        required: false
        type: string
    outputs:
      generated_string:
        description: "The generated string"
        value: ${{ jobs.generate_string_job.outputs.generated_string }}
    
        
jobs:
  generate_string_job:
    runs-on: self-hosted
    outputs:
      generated_string: ${{ steps.remote-action.outputs.string }}
    steps:
    
    - id: remote-action
      uses: mcbillings/composite-actions/first_action@v1
      with:
        given_input: 'This action lives in a different repository'
    - run: echo ${{ steps.remote-action.outputs.string }}
