name: Matrix + Reusable

on: workflow_dispatch
    
jobs:   
  call_workflow: 
    uses: mcbillings/liatrio-chapter-2/.github/workflows/reusable-workflow.yml@main
    with:
        given_input: "Heres an input"
      
  use_output:
    strategy:
      matrix:
        number: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    runs-on: self-hosted
    needs: call_workflow
    steps:
      - run: echo "${{ needs.call_workflow.outputs.generated_string }} - ${{ matrix.number }}"
        
  
