on:
  workflow_call:
    inputs:
      given_input:
        required: true
        type: string
        
jobs:
  generate_string_job:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - id: using action
      uses: mcbillings/liatrio-chapter-2@main
      with:
        given_input: ${{ inputs.given_input }}
