on: 
  workflow_call:
    inputs: 
      given-input:
        required: false
        type: string
        
jobs:
  generate_string:
    runs-on: self-hosted
    steps:
      - uses: mcbillings/composite-actions/first-action@main
        with:
          given_input: ${{ inputs.given-input }}
