on:
  workflow_call:
    inputs:
      given_input:
        required: false
        type: string
    outputs:
      generated_string:
        description: "The generated string"
        value: ${{ jobs.generate_string_job.outputs.generated_string }}
    
        
jobs:
  generate_string_job:
    runs-on: self-hosted
    outputs:
      generated_string: ${{ steps.step2.outputs.generated_string }}
    steps:
    - id: step1
      uses: mcbillings/composite-actions/first_action/@v1
      with:
        given_input: ${{ inputs.given_input }}
    - id: step2
      run: |
        echo ${{ steps.step1.outputs.string }}
        echo "generated_string=${{ steps.step1.outputs.string }}" >> $GITHUB_OUTPUT
