on:
  workflow_call:
    inputs:
      given_input:
        required: true
        type: string
        
jobs:
  generate_string_job:
    outputs:
      generated_string: ${{ steps.put_string.outputs.string }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - id: do_action
    - uses: mcbillings/composite-actions/first_action/@v1
      with:
        given_input: ${{ inputs.given_input }}
    - id: put_string
    - run: echo "string=${{ do_action.outputs.string }}" >> $GITHUB_OUTPUT
