on:
  workflow_call:
    inputs:
      given_input:
        required: true
        type: string
        
jobs:
  generate_string_job:
    runs-on: self-hosted
    steps:
    - uses: mcbillings/composite-actions/first-action@main
      with:
        given_input: ${{ inputs.given_input }}
