name: Using composite action
on: workflow_dispatch

jobs:
  composite_usage:
    runs-on: ubuntu-latest
    name: Generates string from input
    steps:
      - uses: actions/checkout@v3
      - id: using-action
        uses: ../../composite-action.yml@v1
        with:
          given_input: 'Make this is string pls thx'
      - run: echo string given as ${{ steps.using-action.outputs.string }}
