on: workflow_dispatch

jobs:
  composite_usage:
    runs-on: self-runner
    name: Generates string from input
    steps:
      - uses: ./composite-action@v3
      - id: using-action
        with:
          given_input: 'Make this is string pls thx'
      - run: echo string given as ${{ steps.using-action.outputs.string }}
